create database employe_database;
show databases;
use employe_database;

create table emp_record_table(
Emp_id VARCHAR(10) NOT NULL PRIMARY KEY ,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
GENDER VARCHAR (50) NOT NULL,
ROLE VARCHAR(50)NOT NULL,
DEPT VARCHAR (50) NOT NULL,
EXP INT NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
CONTINENT VARCHAR(50) NOT NULL,
SALARY INT NOT NULL,
EMP_RATING INT NOT NULL,
MANAGER_ID VARCHAR(5),
PROJECT_ID VARCHAR(5)
);
DESCRIBE EMP_RECORD_TABLE;

CREATE TABLE PROJ_TABLE(
PROJ_ID VARCHAR(10) NOT NULL PRIMARY KEY,
PROJ_NAME VARCHAR(40) NOT NULL,
DOMAIN VARCHAR(20) NOT NULL,
START_DATE DATE NOT NULL,
CLOSURE_DATE DATE NOT NULL,
DEV_QTR VARCHAR(10) NOT NULL,
STATUS VARCHAR(10) NOT NULL
); 
DESCRIBE PROJ_TABLE;

CREATE TABLE DATA_SCI_TEAM(
EMP_ID VARCHAR(10) NOT NULL primary KEY,
FIRST_NAME VARCHAR(10) NOT NULL,
LAST_NAME VARCHAR(10) NOT NULL,
GENDER VARCHAR(10) NOT NULL,
ROLE VARCHAR(30) NOT NULL,
DEPT VARCHAR(20) NOT NULL,
EXP INT NOT NULL,
COUNTRY varchar(20) NOT NULL,
CONTINENT varchar(20) NOT NULL
);

DESCRIBE DATA_SCI_TEAM;

-- Insert Data in emp_record_table

SELECT * FROM employe_database.EMP_RECORD_TABLE;
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E001', 'ARTHUR ', 'BLACK', 'M', 'PRESIDENT', 'ALL', '20', 'USA ', 'NORTH AMERICA', '16500', '5', 'NULL', 'NULL');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E005', 'ERIC', 'HOFFMAN', 'M', 'LEAD DATA SCIENTIST', 'FINANACE', '11', 'USA', 'NORTH AMERICA', '8500', '3', 'E103', 'P105');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E010', 'WILLIAM', 'BUTLER', 'M', 'LEAD DATA SCIENTIST', 'AUTOMOTIVE', '12', 'FRANCE', 'EUROPE', '9000', '2', 'E428', 'P204');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E052', 'DIANNA', 'WILSON', 'F', 'SENIOR DATA SCIENTIST', 'HEALTHCARE', '6', 'CANADA', 'NORTH AMERICA', '5500', '5', 'E083', 'P103');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E057', 'DORORTHY', 'WILSON', 'F', 'SENIOR DATA SCIENTIST', 'HEALTHCARE', '9', 'USA', 'NORTH AMERICA', '7700', '1', 'E083', 'P302');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`) VALUES ('E083', 'PATRICK', 'VOLTZ', 'M', 'MANAGER', 'HEALTHCARE', '15', 'USA', 'NORTH AMERICA', '9500', '5', 'E001');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`) VALUES ('E103', 'EMILY', 'GROVE', 'F', 'MANAGER', 'FINANACE', '14', 'CANADA', 'NORTH AMERICA', '10500', '4', 'E001');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E204', 'KARENE ', 'NOVAK', 'F', 'SENIOR DATA SCIENTIST', 'AUTOMOTIVE', '8', 'GERMANY', 'EUROPE', '7500', '5', 'E428', 'P204');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E245', 'NIAN ', 'ZHEN', 'M', 'SENIOR DATA SCIENTIST', 'RETAIL', '6', 'CHINA', 'ASIA', '6500', '2', 'E583', 'P109');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E260', 'ROY', 'COLLINS', 'M', 'SENIOR DATA SCIENTIST', 'RETAIL', '7', 'INDIA', 'ASIA', '7000', '3', 'E583', 'NA');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E403', 'STEVE', 'HOFFMAN', 'M', 'ASSOCIATE DATA SCIENTIST', 'FINANACE', '4', 'USA', 'NORTH AMERICA', '5000', '3', 'E103', 'P105');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`) VALUES ('E428', 'PETE', 'ALLEN', 'M', 'MANAGER', 'AUTOMOTIVE', '14', 'GERMANY', 'EUROPE', '11000', '4', 'E001');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E478', 'DAVID', 'SMITH', 'M', 'ASSOCIATE DATA SCIENTIST', 'RETAIL', '3', 'COLOMBIA', 'SOUTH AMERICA', '4000', '4', 'E583', 'P109');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E505', 'CHAD', 'WILSON', 'M', 'ASSOCIATE DATA SCIENTIST', 'HEALTHCARE', '5', 'CANADA', 'NORTH AMERICA', '5000', '2', 'E583', 'P103');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E532', 'CLAIRE', 'BRENNAN', 'F', 'ASSOCIATE DATA SCIENTIST', 'AUTOMOTIVE', '3', 'GERMANY', 'EUROPE', '4300', '1', 'E428', 'P204');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`) VALUES ('E583', 'JANET', 'HALE', 'F', 'MANAGR', 'RETAIL', '14', 'COLOMBIA', 'SOUTH AMERICA', '10000', '2', 'E001');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`) VALUES ('E612', 'TRACY', 'NORRIS', 'F', 'MANAGER', 'RETAIL', '13', 'INDIA', 'ASIA', '8500', '4', 'E001');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E620', 'KATRINA', 'ALLEN', 'F', 'JUNIOR DATA SCIENTIST', 'RETAIL', '2', 'INDIA', 'ASIA', '3000', '1', 'E612', 'P406');
INSERT INTO `employe_database`.`EMP_RECORD_TABLE` (`Emp_id`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`, `SALARY`, `EMP_RATING`, `MANAGER_ID`, `PROJECT_ID`) VALUES ('E640', 'JENIFER', 'JHONES', 'F', 'JUNIOR DATA SCIENTIST', 'RETAIL', '1', 'COLOMBIA', 'SOUTH AMERICA', '2800', '4', 'E612', 'P406');

SELECT * FROM employe_database.PROJ_TABLE;

INSERT INTO `employe_database`.`PROJ_TABLE` (`PROJ_ID`, `PROJ_NAME`, `DOMAIN`, `START_DATE`, `CLOSURE_DATE`, `DEV_QTR`, `STATUS`) VALUES ('P103', 'Drug Discovery', 'Healthcare', '2021-04-06', '2021-06-20', 'Q1', 'DONE');
INSERT INTO `employe_database`.`PROJ_TABLE` (`PROJ_ID`, `PROJ_NAME`, `DOMAIN`, `START_DATE`, `CLOSURE_DATE`, `DEV_QTR`, `STATUS`) VALUES ('P105', 'Fraud Detection', 'Finance', '2021-04-11', '2021-06-25', 'Q1', 'DONE');
INSERT INTO `employe_database`.`PROJ_TABLE` (`PROJ_ID`, `PROJ_NAME`, `DOMAIN`, `START_DATE`, `CLOSURE_DATE`, `DEV_QTR`, `STATUS`) VALUES ('P109', 'Market Basket Analysis', 'Retail', '2021-04-12', '2021-06-30', 'Q1', 'DELAYED');
INSERT INTO `employe_database`.`PROJ_TABLE` (`PROJ_ID`, `PROJ_NAME`, `DOMAIN`, `START_DATE`, `CLOSURE_DATE`, `DEV_QTR`, `STATUS`) VALUES ('P204', 'Supply Chain Management', 'Automotive', '2021-07-15', '2021-09-28', 'Q2', 'WIP');
INSERT INTO `employe_database`.`PROJ_TABLE` (`PROJ_ID`, `PROJ_NAME`, `DOMAIN`, `START_DATE`, `CLOSURE_DATE`, `DEV_QTR`, `STATUS`) VALUES ('P302', 'Early Detection of cancer', 'Healthcare', '2021-10-08', '2021-12-18', 'Q3', 'YTS');
INSERT INTO `employe_database`.`PROJ_TABLE` (`PROJ_ID`, `PROJ_NAME`, `DOMAIN`, `START_DATE`, `CLOSURE_DATE`, `DEV_QTR`, `STATUS`) VALUES ('P406', 'Customer Sentiment Analysis', 'Retail', '2021-07-09', '2021-09-24', 'Q2', 'WIP');

select * from employe_database.data_sci_team;

INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E005', 'ERIC', 'HOFFMAN', 'M', 'LEAD DATA SCIENTIST', 'FINANCE', '11', 'USA', 'NORTH AMERICA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E010', 'WILLIAM', 'BUTTLER', 'M', 'LEAD DATA SCIENTIST', 'AUTOMOTIVE', '12', 'FRANCE', 'EUROPE');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E052', 'DIANNA', 'WILSON', 'F', 'SENIOR DATA SCIENTIST', 'HEALTHCARE', '6', 'CANADA', 'NORTH AMERICA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E057', 'DOROTHY', 'WILSON', 'F', 'SENIOR DATA SCIENTIST', 'HEALTHCARE', '9', 'USA', 'NORTH AMERICA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E204', 'KARENE', 'NOWAK', 'F', 'SENIOR DATA SCIENTIST', 'AUTOMOTIVE', '8', 'GERMANY', 'EUROPE');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E245', 'NIAN', 'ZHEN', 'M', 'SENIOR DATA SCIENTIST', 'RETAIL', '6', 'CHINA', 'ASIA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E260', 'ROY', 'COLLINS', 'M', 'SENIOR DATA SCIENTIST', 'RETAIL', '7', 'INDIA', 'ASIA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E403', 'STEVE', 'HOFFMAN', 'M', 'ASSOCIATE DATA SCIENTIST', 'FINANCE', '4', 'USA', 'NORTH AMERICA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E478', 'DAVID', 'SMITH', 'M', 'ASSOCIATE DATA SCIENTIST', 'REATAIL', '3', 'COLOMBIA', 'SOUTH AMERICA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E505', 'CHAD', 'WILSON', 'M', 'ASSOCIATE DATA SCIENTIST', 'HEALTHCARE', '5', 'CANADA', 'NORTH AMERICA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E532', 'CLAIRE', 'BRENNAN', 'F', 'ASSOCIATE DATA SCIENTIST', 'AUTOMOTIVE', '3', 'GERMANY', 'EUROPE');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E620', 'KATRINA', 'ALLEN', 'F', 'JUNIOR DATA SCIENTIST', 'RETAIL', '2', 'INDIA', 'ASIA');
INSERT INTO `employe_database`.`data_sci_team` (`EMP_ID`, `FIRST_NAME`, `LAST_NAME`, `GENDER`, `ROLE`, `DEPT`, `EXP`, `COUNTRY`, `CONTINENT`) VALUES ('E640', 'JENIFER', 'JHONES', 'F', 'JUNIOR DATA SCIENTIST', 'RETAIL', '1', 'COLOMBIA', 'SOUTH AMERICA');

-- DEFINE MAX SALARY AND MIN SALARY
SELECT ROLE, MIN(SALARY) AS MINSALARY , MAX(SALARY) AS MAXSALARY
FROM EMP_RECORD_TABLE
GROUP BY ROLE;

-- EMP RATING IS LESS THAN TWO
SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING
FROM EMP_RECORD_TABLE
WHERE EMP_RATING<2;

-- Max salary
SELECT MAX(SALARY) AS Maximum_Salary FROM emp_record_table;

-- EMP RATING IS GREATER THAN FOUR
SELECT EMP_ID,FIRST_NAME,LAST_NAME, GENDER , DEPT, EMP_RATING
FROM EMP_RECORD_TABLE
WHERE EMP_RATING >4;

-- EMP_RATING BETWEEN TWO AND FOUR

SELECT EMP_ID FIRST_NAME, LAST_NAME , GENDER,DEPT,EMP_RATING
FROM EMP_RECORD_TABLE
WHERE EMP_RATING BETWEEN 2 AND 4;

--  Write a query to calculate the bonus for all the employees, based on their ratings and salaries (Use the formula: 5% of salary * employee rating).
SELECT FIRST_NAME, LAST_NAME, SALARY,((SALARY *.05)*emp_rating) AS Bonus
FROM EMP_RECORD_TABLE;

-- name of each project and the number of employees working on each project.
SELECT PROJ_Name, COUNT(EMP_id) AS Number_of_Employees
FROM emp_record_table 
JOIN proj_table p ON PROJ_ID = PROJECT_ID
GROUP BY PROJ_Name;

-- write query to assign ranks to each employee based on their experience. Take data from the employee record  table.  
SELECT FIRST_NAME, LAST_NAME, exp as experience, 
DENSE_RANK() OVER (ORDER BY exp DESC) exp_rank 
FROM emp_record_table;










